### PR TITLE
TeamCP & CountdownCP Change

### PR DESCRIPTION
**Pull request by Serializator**
Add TeamCP.
Add delay to the repeating task of the CountdownCP.

### CODE REVIEW

**Comment by Rojoss** [comment]
Thanks, but gonna need a quite a bit more work.
I've not written documentation for this component yet and not all the backend for it is done yet.
But it'll need a Team class for sure as teams will be quite a bit more complex than that.
Also, for adding team and such you're just silently returning either throw an exception or return the previous team when it exists and otherwise the new team. (or boolean)

It's probably best to leave components till most of the backend stuff is done.
For example it will need to use the scoreboard API and NPC API etc.
I've not really written documentation for the components because the backend is not done yet.

**Comment by Rojoss** [comment]
Regarding lobby: http://gameboxx.info/cp/lobby

**Comment by Serializator** [comment]
Sorry for the messy PR, a couple of things went wrong in my CLI and I'm quite nitpicky on my PR titles x-)
_LobbyCP_ shouldn't even have been in the PR yet.

**Comment by Rojoss** [comment]
I'm gonna leave this one open for now.

**Comment by Serializator** [comment]
np

**Pull request closed without merging**
